<Project>
  <PropertyGroup>
    <VersionMajor>2</VersionMajor>
    <VersionMinor>0</VersionMinor>
    <VersionBase>$(VersionMajor).$(VersionMinor)</VersionBase>
    <Authors>LenovoLegionToolkit-Team</Authors>
    <Copyright>Copyright © 2026</Copyright>
    <RepositoryUrl>https://github.com/LenovoLegionToolkit-Team/PresentMonFps</RepositoryUrl>
    <PackageProjectUrl>https://github.com/LenovoLegionToolkit-Team/PresentMonFps</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
